id: I3754FB5F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:28:55+00:00'
last_modified: '2022-06-08T06:55:57.944675+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29152
  title: འབྲུག་པ་ཀུན་ལེགས་ཀྱི་རང་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    13BB:
      image_group_id: I1KG14837
      title: ''
      total_pages: 94
      order: 1
      base_file: 13BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
