id: P006798
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W29152
  title: འབྲུག་པ་ཀུན་ལེགས་ཀྱི་རང་རྣམ།
  author: ''
  volumes:
    83d74b028d8f49098a5d092e76bca968:
      image_group_id: I1KG14837
      title: ''
      volume_number: 1
      total_pages: 94
      base_file: v001.txt
